//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by D:\Work\styck\Vacs Client\usengl\usengl.rc
//
#define IDD_SEQUENCE_WINDOW             101
#define IDD_PRF_MIDI                    102
#define MENU_TVN_POPUP                  102
#define IDD_PRF_GENERAL                 103
#define SAC_MAIN_MENU                   103
#define IDD_PRF_MIXER_CHANNELPORT       104
#define IDD_PRF_VIEWS                   105
#define IDD_PRF_ACTIONS                 106
#define IDD_GROUPS                      107
#define IDD_SEQ_UPDATE_PROP             108
#define MENU_LVN_POPUP                  110
#define IDD_SMPTE_DISPLAY               141
#define IDD_PRF_MTC                     142
#define IDC_PRF_MTC_IN                  1000
#define IDC_PRF_MIDI_IN                 1001
#define IDC_PRF_MTC_OUT                 1001
#define IDC__PRF_SAVESTATE_EXIT         1002
#define IDC_PRF_MIDI_OUT                1002
#define IDBTN_SEQ_ADD                   1002
#define IDC_PRF_AUTOSAVE                1003
#define IDBTN_SEQ_UPDATE                1003
#define IDC_PRF_SAVEWINDOWPOS           1004
#define IDBTN_SEQ_DELETE                1004
#define IDC_PRF_TRACKINGWINDOWON        1005
#define IDSLIDER_SEQ_MORPH              1005
#define IDC_PRF_SEQCHANNELS             1006
#define IDBTN_SEQ_EXPAND                1006
#define IDC_MIXER_IN                    1007
#define IDBTN_SEQ_EXPAND2               1007
#define IDC_PRF_MIXERIN_CHANNEL         1008
#define IDC_MIXER_OUT                   1009
#define IDC_PRF_FULLVIEW                1009
#define IDC_PRF_MIXERIN_PORT            1010
#define IDC_PRF_ZOOMVIEW                1010
#define IDC__PRF_AUTOEXEC_CUES          1011
#define IDC_PRF_MIXEROUT_CHANNEL        1011
#define IDBTN_SEQ_NEXT                  1011
#define IDC_PRF_ACTIVATEONFIRST         1012
#define IDC_PRF_MIXEROUT_PORT           1012
#define IDBTN_SEQ_PREV                  1012
#define IDC_PRF_SHOWSEQVIEW_ONGO        1013
#define IDC_PRF_ENABLE_KBOARD_NAVIGATION 1014
#define IDBTN_SEQ_TOP                   1014
#define IDE_PRF_SMPTE_MTC               1015
#define IDBTN_SEQ_BOTTOM                1015
#define IDBTN_SEQ_PLAY                  1016
#define IDTREE_SEQUENCE                 1017
#define IDLIST_SEQ_EVENTS               1018
#define IDC_MTC_READOUT                 1019
#define IDC_GROUP_ADD                   1020
#define IDC_GROUP_UPADTE                1021
#define IDC_GROUP_DELETE                1022
#define IDC_GROUP_HIDECONTROLS          1023
#define IDC_GROUP_LIST                  1024
#define IDC_CANCEL_GROUP                1025
#define IDC_DONOT_PROP                  1027
#define IDC_PROP_ALL                    1028
#define IDC_PROP_CUSTOM                 1029
#define IDC_INP_VOLUME                  1030
#define IDC_INP_MUTE                    1031
#define IDC_INP_EQ                      1032
#define IDC_INP_GATE                    1033
#define IDC_INP_COMP                    1034
#define IDC_SHOW_CHANGES                1035
#define IDC_USE_AUTO                    1036
#define ID_DEFAULTBOX                   1037
#define IDS_QUIT_MESSAGE                2025
#define IDS_DCXBIN_FILE_FAILED          2026
#define IDS_ERR_LOAD_BITMAP             2030
#define IDS_ERR_RESOURCE_ZONES          2031
#define IDS_ERR_ALLOCATE_MEMORY         2032
#define IDS_ERR_OPEN_MIDI_IN            2034
#define IDS_ERR_OPEN_MIDI_OUT           2035
#define IDS_ERR_MIDI_DEV_OUT            2036
#define IDS_ERR_MIDI_DEV_IN             2037
#define IDS_ERR_CREATING_FILE           2038
#define IDS_ERR_OPENING_FILE            2039
#define IDS_WRONG_VIEWSET               2040
#define IDS_ERR_RESOURCE_DESCRIPTOR     2041
#define IDS_ERR_ZONE_MAP_COUNT          2042
#define IDS_ERR_ZONEMAP_RESOURCE        2043
#define IDS_ERR_ADD_MIDI_IN_BUFFER      2044
#define IDS_ERR_CREATING_PALETTE        2045
#define IDS_ERR_CREATE_WINDOW           2046
#define IDS_ERR_INVALID_CONTROL         2047
#define IDS_ERR_LOCATING_RESOURCE       2048
#define IDS_ERR_LOADING_RESOURCE        2049
#define IDS_ERR_MAX_WINDOW              2050
#define IDS_ERR_GET_SERVER_DATA         2051
#define IDS_ERR_EVENT_HANDLE            2052
#define IDS_CHANGES_MESSAGE             2052
#define IDS_FULL_VIEW_640               2100
#define IDS_FULL_VIEW_800               2101
#define IDS_FULL_VIEW_1024              2102
#define IDS_ZOOM_VIEW_640               2103
#define IDS_ZOOM_VIEW_800               2104
#define IDS_ZOOM_VIEW_1024              2105
#define IDS_PREF_SAVED                  2106
#define IDS_INCOMP_PREF_FILE            2107
#define IDS_NEW_VER_PRF_FILE            2108
#define IDS_NONE                        2109
#define IDS_DEVICENOTFOUND              2110
#define IDS_PREF_NOTSAVED               2111
#define IDS_ERR_REGISTER_CLASS          2112
#define IDS_ERR_APPLY_PREF              2113
#define IDS_ERR_READING_FILE            2114
#define IDS_ERR_NO_SUPPORT_DIRECTORIES  2200
#define IDS_INVALID_DEVICE_MAP          2500
#define IDS_INVALID_DEVICE_MASTER_MANY  2501
#define IDS_INVALID_DEVICE_CUE_MANY     2502
#define IDS_INVLAID_DEVICE_AUX_COMBO    2503
#define IDS_INVALID_DEVICE_MAP_AUX_MANY 2504
#define IDS_INVALID_DEVICE_MAP_MATRIX_MANY 2505
#define IDS_INVALID_DEVICE_NO_MASTER    2506
#define IDS_FILE_DEFEXT                 3000
#define IDS_DEFINITION_FAILED           3500
#define IDS_DEFINITION_FAILED2          3501
#define IDS_GROUP_WINDOW_TITLE          3700
#define IDS_SEQUENCE_WINDOW_TITLE       3999
#define IDS_FIRSTSEQCOLUMN              4000
#define IDS_SEQCOLUMN2                  4001
#define IDS_SEQCOLUMN3                  4002
#define IDS_SEQCOLUMN4                  4003
#define IDS_RECALL_ALL_CONTROLS         4004
#define IDS_CDEF_CONTROLNAME_NOTFOUND   5000
#define IDS_DCX32_LOADED                5001
#define IDS_MULTIPLE_APPLICATIONS_RUNNING 5001
#define IDSS_TEXT_1                     6000
#define IDSS_TEXT_2                     6001
#define IDM_F_SAVEPREFERENCES           32004
#define IDM_F_EXIT                      32006
#define IDM_V_FULLCONSOLE               32007
#define IDM_V_FULLZOOM                  32008
#define IDM_A_RECEIVE_SMPTE             32019
#define IDM_A_UPDATEMIDIMANUAL          32020
#define IDM_H_ABOUT                     32032
#define IDM_WINDOWTILE                  32033
#define IDM_WINDOWCASCADE               32034
#define IDM_WINDOWICONS                 32035
#define IDM_WINDOWCLOSEALL              32036
#define IDM_V_CANCELGROUPS              32037
#define IDM_V_CANCELCUES                33000
#define IDM_F_OPEN_FILE                 40001
#define IDM_F_SAVE_FILE                 40002
#define IDM_F_UPDATE_FILE               40004
#define IDS_MIXFILE_SAVED               40005
#define IDM_V_SEQUENCE                  40005
#define IDS_MIXFILE_NOTSAVED            40006
#define MENU_TVN_ADD                    40007
#define IDS_DELETE_SEQUENCE_ENTRY       40007
#define IDS_INCOMP_MIX_FILE             40008
#define MENU_TVN_UPDATE                 40008
#define MENU_TVN_PROPERTIES             40011
#define ID_RECALL                       40012
#define MENU_TVN_DELELTE                40013
#define MENU_TVN_FINDSMPTE              40015
#define MENU_TVN_FINDNAME               40016
#define MENU_TVN_FINDEVENT              40017
#define IDM_F_CONDEF_PREFERENCES        40018
#define IDM_V_FULLZOOM_MASTER           40019
#define IDM_V_FULLZOOM_AUX              40020
#define IDM_REQUEST_SETUPDATA           40021
#define IDM_START_VU_READ               40022
#define IDM_VU_LINEAR                   40023
#define IDM_VU_LOG                      40024
#define IDM_STOP_VU_READ                40025
#define IDM_RESET_ALL_CONTROLS          40026
#define IDM_V_GROUP                     40027
#define IDM_RECAL_ALL_CONTROLS          40028
#define IDM_START_TRACKING_WINDOW       40029
#define IDM_V_PROP_FILTER               40030
#define IDS_DEFINITION_FAILED3          40031
#define IDM_S_PLAY                      40032
#define IDM_S_RECALL_CURRENT            40033
#define IDM_S_PAUSE                     40034
#define IDM_S_GOTO_FIRST                40035
#define IDM_S_BACK                      40036
#define IDM_S_NEXT                      40037
#define IDM_S_GOTO_LAST                 40038
#define IDM_F_SAVE_FILE_AS              40039
#define IDM_RESETBUS                    40040
#define IDM_H_INFO                      40041
#define MENU_TVN_RENAME                 40042
#define MENU_LVN_ADD                    40046
#define MENU_LVN_DELETE                 40047
#define MENU_LVN_RENAME                 40048
#define MENU_LVN_UPDATE                 40049
#define MENU_LVN_CANCEL                 40050
#define IDM_SOLO_CUE_MODE               40051
#define IDM_UPDOWNSCROLL_SPEED          40052
#define IDM_GENERATE_DLLIST             40100

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        111
#define _APS_NEXT_COMMAND_VALUE         40053
#define _APS_NEXT_CONTROL_VALUE         1038
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
